go_cqhttp:
  host: '127.0.0.1'
  port: '5701'
  user_id: 123456
  standalone: true

bot:
  admin:
    - 123456
  enabled_groups:
    - 7890

enginetribe_api:
  host: "http://enginetribe.gq:30000"
  api_key: "enginetribe"
  token: "123"

webhook:
  host: '0.0.0.0'
  port: 5583